Repository quozd/awesome-dotnet, pull requests merged in 2018-08, with the labels that each got.

#679 Add hybridizer in compiler section
  README.md
Labels: Incorrect PR format, Project has no issue tracker

#637 Add NReco PivotData
  README.md
Labels: Community decision required

#667 Add ML.NET
  README.md
Labels: Project is possibly too new
