Repository quozd/awesome-dotnet, pull requests merged in 2020-02, with the labels that each got.

#770 Added https://github.com/ivanpaulovich/dotnet-clean-architecture
  README.md
Labels: Project is possibly not awesome, Project is possibly too new, Project is possibly too small

#777 Added StringDB https://github.com/SirJosh3917/StringDB
  README.md
Labels: PR requires update

#793 Add "NaturalSort.Extension"
  README.md
Labels: PR requires update

#804 add CommandDotNet to cli section
  README.md
Labels: PR requires update

#814 Add Outlook Redemption (Office)
  README.md
Labels: Community decision required

#827 Add Smaragd
  README.md
Labels: Community decision required, Project is possibly too small

#828 Added Cloudsmith (Package Management SaaS)
  README.md
Labels: Community decision required

#829 Add Db4o-GPL to Database
  README.md
Labels: Community decision required, Project is possibly not awesome, Project is possibly too small

#865 Added GemBox.Bundle libraries
  README.md
Labels: PR requires update

#876 Add Unchase.Odata.Connectedservice
  README.md
Labels: Community decision required, Project is possibly too small
